# Generated by Django 4.2.2 on 2023-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='price',
        ),
        migrations.AddField(
            model_name='catalog',
            name='addition',
            field=models.TextField(blank=True, verbose_name='Дополнительные опции'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Комлектация'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='materials',
            field=models.TextField(blank=True, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='permitted_size',
            field=models.TextField(blank=True, verbose_name='Допустимые размеры'),
        ),
    ]
